services:
  springboot_python_back:
    image: springboot_python_back:latest
    container_name: "springboot_python"
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh
      - /root/config
    expose:
      - "8000"
    depends_on:
      - springboot_python_db
    restart: always
    networks:
      - "springboot_python_network"
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.springboot-back.rule=Host(`springboot.flo-isk.fr`)"
      - "traefik.http.routers.springboot-back.entrypoints=websecure"
      - "traefik.http.routers.springboot-back.tls=true"
      - "traefik.docker.network=traefik-net"

  springboot_python_db:
    container_name: "springboot_python_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    networks:
      - "springboot_python_network"

  springboot_python_pgadmin:
    container_name: "springboot_python_pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    expose:
      - "80"
    depends_on:
      - springboot_python_db
    restart: always
    env_file:
      - .env
    networks:
      - "springboot_python_network"

volumes:
  postgres_data:

networks:
  springboot_python_network:
    driver: bridge
  traefik-net:
    external: true
