"""Add book table

Revision ID: b8060a8cd847
Revises: d9a6ed2c9e62
Create Date: 2025-02-20 17:33:14.439468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8060a8cd847'
down_revision: Union[str, None] = 'd9a6ed2c9e62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('students', sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'students', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='unique')
    op.drop_column('students', 'email')
    op.drop_table('books')
    # ### end Alembic commands ###
